### PR TITLE
Added Java starter with setup instructions

### PR DESCRIPTION
**Pull request by imattman**
Added a java starter skeleton that uses the [javaspark](http://sparkjava.com/) micro framework.

### CODE REVIEW

**Comment by imattman** [comment]
There is some inconsistency in URLs across the language starters.
I went with `/users` instead of people, but used the plural path even with a singular resource.

| Language     | HTTP Verb | Path                         |
|-------------|------------|---------------------|
| **python**  |  GET           |  /users                      |
| **python**  |  GET           |  /user/**:id**            |
| **python**  |  POST         |  /user/add               |
| **ruby**      |  GET           |  /people                    |
| **ruby**      |  GET           |  /people/**:id**        |
| **ruby**      |  POST         |  /people/add           |
| **java**       |  GET           |  /users                       |
| **java**       |  GET           |  /user**s**/**:id**    |
| **java**       |  POST         |  /user**s**            |

I'm happy to change it to be more like one of the other projects.   That and any other feedback is welcome.

**Comment by Errolyn** [comment]
That is a good call out! For now let's keep them the same since people have already used those paths for their APIs. We will probably make some changes the next time we do an API challenge. Thanks for creating a Java starter for people. It will be an exelent resource.

Feel free to merge your code.

**Comment by imattman** [comment]
I don't have perms to merge it myself.  I'll need some assistance 😃

**Comment by jarrighi** [comment]
Part of this challenge is designing the url structure, so I think having some differences is actually nice. We could call this out in the activity setup if we do this again. Thanks again, Matt!

**Pull request merged**
